### ISSUE TITLE
LookupResult should contain properly named getters

### ISSUE THREAD

**Issue by Yarin78** [spotify/dns-java#14]
The getters should be called getHost(), getPort() etc. Failure to do so prevents automatic Jackson serialization.

**Comment by pettermahlen** [comment]
I think this is more of a Jackson configuration issue than something that needs to be solved here?

**Comment by rouzwawi** [comment]
Agreed. This can be resolved with a generic [`PropertyNamingStrategy`](http://wiki.fasterxml.com/JacksonFeaturePropertyNamingStrategy).
