### ISSUE TITLE
Race condition when registering a listener with a watcher.

### ISSUE THREAD

**Issue by mikaelgoldmann** [spotify/dns-java#16]
This test seems to show that there is a race condition when registering i listener.

https://github.com/mikaelgoldmann/dns-java/commit/50919573f243db83750e7ee617a46f872dd2152a

It appears that when setting fire = true, if there is also a change in the watched record, the listener can be called by two threads concurrently, possibly seeing the old result after the new result.

**Comment by pettermahlen** [comment]
Fixed via #17
