### ISSUE TITLE
Depending on jsr305 is breaking java modules

### ISSUE THREAD

**Issue by tqh** [spotify/dns-java#33]
Depending on com.google.code.findbugs:jsr305:jar:2.0.1 is breaking java modules
See https://blog.codefx.org/java/jsr-305-java-9/ and https://www.google.com/search?q=jsr305%20split%20package for info.

With modules you can slim down your java app including runtime with a few hundred megabytes. So it would be nice to do this. 

As you only use @Nullable in three files (one is a test) it should be trivial to do:
 * src/main/java/com/spotify/dns/DnsException.java
 * src/main/java/com/spotify/dns/ServiceResolvingChangeNotifier.java
 * src/test/java/com/spotify/dns/ServiceResolvingChangeNotifierTest.java

**Comment by rouzwawi** [comment]
Resolved by #38 
Will be part of next release
