### ISSUE TITLE
Not working when used in Tomcat Servlet

### ISSUE THREAD

**Issue by dsushil2000** [spotify/dns-java#35]
This library unable to fetch the information when used in Rest API? Any issues? Works standalone JVM.

**Comment by pettermahlen** [comment]
There are no known issues with the library itself. It's more likely to be due to how you launch Tomcat, such as if it's in a container that has something odd in its DNS lookup configuration or something else.

**Comment by dsushil2000** [comment]
Thanks. There were issues with DNS scan or sort of. Admin made some changes and it's working now.
